services:
  db:
    image: postgres:15
    container_name: maintenance-tracker-db
    environment:
      - POSTGRES_DB=tracker
      - POSTGRES_USER=tracker
      - POSTGRES_PASSWORD=tracker
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    container_name: maintenance-tracker-redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  app:
    build: .
    image: iacobstev/maintenance-tracker-app:${IMAGE_TAG}
    container_name: maintenance-tracker-app
    environment:
      - DB_TYPE=postgres
      - PG_HOST=db
      - PG_PORT=5432
      - PG_DB=tracker
      - PG_USER=tracker
      - PG_PASSWORD=tracker
    ports:
      - "5000:5000"
    depends_on:
      - db
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: maintenance-tracker-frontend
    ports:
      - "8080:80"
    environment:
      API_URL: http://localhost:5000
    depends_on:
      - app
    restart: unless-stopped

  worker:
    build:
      context: .
      dockerfile: worker/Dockerfile
    container_name: maintenance-tracker-worker
    environment:
        - REDIS_URL=redis://redis:6379/0
        - DB_TYPE=postgres
        - PG_HOST=db
        - PG_PORT=5432
        - PG_DB=tracker
        - PG_USER=tracker
        - PG_PASSWORD=tracker
    depends_on:
      - redis
    restart: unless-stopped

  beat:
    build:
      context: .
      dockerfile: worker/Dockerfile
    container_name: maintenance-tracker-beat
    command: celery -A app.celery_app.celery_app beat --loglevel=info --schedule=/tmp/celerybeat-schedule
    environment:
      - REDIS_URL=redis://redis:6379/0
      - DB_TYPE=postgres
      - PG_HOST=db
      - PG_PORT=5432
      - PG_DB=tracker
      - PG_USER=tracker
      - PG_PASSWORD=tracker
    depends_on:
      - redis
      - db
    restart: unless-stopped

volumes:
  pgdata:
