apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.worker.name }}
spec:
  replicas: {{ .Values.worker.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.worker.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.worker.name }}
    spec:
      containers:
        - name: worker
          image: "{{ .Values.worker.image.repository }}:{{ .Values.worker.image.tag }}"
          command: {{ .Values.worker.command | toJson }}
          args: {{ .Values.worker.args | toJson }}
          env:
            {{- range $key, $value := .Values.worker.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
