apiVersion: apps/v1
kind: Deployment
metadata:
  name: personal-tracker-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: personal-tracker-frontend
  template:
    metadata:
      labels:
        app: personal-tracker-frontend
    spec:
      containers:
        - name: frontend
          image: iacobstev/personal-tracker-frontend:v1
          ports:
            - containerPort: 80
          volumeMounts:
            - name: config-volume
              mountPath: /usr/share/nginx/html/config.js
              subPath: config.js
      volumes:
        - name: config-volume
          configMap:
            name: frontend-config
