apiVersion: apps/v1
kind: Deployment
metadata:
  name: personal-tracker-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: personal-tracker-worker
  template:
    metadata:
      labels:
        app: personal-tracker-worker
    spec:
      containers:
        - name: worker
          image: iacobstev/personal-tracker-app:latest
          command: ["celery"]
          args: ["-A", "app.celery_app.celery_app", "worker", "--loglevel=info"]
          env:
            - name: DB_TYPE
              value: "postgres"
            - name: PG_HOST
              value: "postgres"
            - name: PG_USER
              value: "postgres"
            - name: PG_PASSWORD
              value: "postgres"
            - name: PG_DB
              value: "personal_tracker"
            - name: CELERY_BROKER_URL
              value: "redis://redis:6379/0"
            - name: CELERY_RESULT_BACKEND
              value: "redis://redis:6379/0"
