app:
  name: maintenance-tracker-app
  replicas: 2

image:
  repository: iacobstev/maintenance-tracker-app
  tag: b663c00faa52c1158941456dccab590e6028085b
  pullPolicy: Always

service:
  type: ClusterIP
  port: 5000
  targetPort: 5000

ingress:
  enabled: true
  name: maintenance-tracker-ingress
  className: traefik
  host: tracker.local
  path: /
  pathType: Prefix

configMap:
  name: app-config

secret:
  name: app-secret
  pgPasswordKey: PG_PASSWORD

probes:
  path: /health
  liveness:
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 2
    failureThreshold: 3
  readiness:
    initialDelaySeconds: 15
    periodSeconds: 5
    timeoutSeconds: 2
    failureThreshold: 6

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "250m"
    memory: "256Mi"

worker:
  name: maintenance-tracker-worker
  replicas: 1
  image:
    repository: iacobstev/maintenance-tracker-app
    tag: b663c00faa52c1158941456dccab590e6028085b
  command: ["celery"]
  args: ["-A", "app.celery_app.celery_app", "worker", "--loglevel=info"]
  env:
    DB_TYPE: "postgres"
    PG_HOST: "maintenance-tracker-postgresql"
    PG_USER: "tracker"
    PG_DB: "tracker"
    CELERY_BROKER_URL: "redis://maintenance-tracker-redis-master:6379/0"
    CELERY_RESULT_BACKEND: "redis://maintenance-tracker-redis-master:6379/0"

beat:
  name: maintenance-tracker-beat
  replicas: 1
  image:
    repository: iacobstev/maintenance-tracker-app
    tag: b663c00faa52c1158941456dccab590e6028085b
  command: ["celery"]
  args: ["-A", "app.celery_app.celery_app", "beat", "--loglevel=info", "--schedule=/tmp/celerybeat-schedule"]

frontend:
  name: maintenance-tracker-frontend
  replicas: 1
  image:
    repository: iacobstev/maintenance-tracker-frontend
    tag: b663c00faa52c1158941456dccab590e6028085b
  containerPort: 80
  service:
    type: NodePort
    port: 80
    targetPort: 80
    nodePort: 30080
  configMap:
    name: frontend-config
    apiUrl: "http://maintenance-tracker-app:5000"

redis:
  architecture: standalone
  auth:
    enabled: false
  master:
    persistence:
      enabled: false

db:
  port: 5432

postgresql:
  auth:
    username: tracker
    existingSecret: app-secret
    secretKeys:
      userPasswordKey: PG_PASSWORD
      adminPasswordKey: POSTGRES_PASSWORD
    database: tracker
  primary:
    persistence:
      enabled: true
      size: 1Gi

appConfig:
  name: app-config
  data:
    DB_CONNECT_DELAY: "3"
    DB_CONNECT_RETRIES: "10"
    DB_TYPE: "postgres"
    PG_DB: "tracker"
    PG_HOST: "maintenance-tracker-postgresql"
    PG_PORT: "5432"
    PG_USER: "tracker"

workerResources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

beatResources:
  requests:
    cpu: "50m"
    memory: "64Mi"
  limits:
    cpu: "200m"
    memory: "256Mi"

frontendResources:
  requests:
    cpu: "50m"
    memory: "64Mi"
  limits:
    cpu: "200m"
    memory: "128Mi"

securityContext:
  runAsUser: 10001
  runAsGroup: 10001
