apiVersion: apps/v1
kind: Deployment
metadata:
  name: personal-tracker-beat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: personal-tracker-beat
  template:
    metadata:
      labels:
        app: personal-tracker-beat
    spec:
      containers:
        - name: beat
          image: iacobstev/personal-tracker-app:v4
          command: ["celery"]
          args: ["-A", "app.celery_app.celery_app", "beat", "--loglevel=info"]
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secret
