app:
  name: personal-tracker-app
  replicas: 2

image:
  repository: iacobstev/personal-tracker-app
  tag: latest
  pullPolicy: Always

service:
  type: NodePort
  port: 5000
  targetPort: 5000

ingress:
  enabled: true
  name: personal-tracker-ingress
  className: traefik
  host: tracker.local
  path: /
  pathType: Prefix

configMap:
  name: app-config

secret:
  name: app-secret
  pgPasswordKey: PG_PASSWORD

probes:
  path: /health
  liveness:
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 2
    failureThreshold: 3
  readiness:
    initialDelaySeconds: 15
    periodSeconds: 5
    timeoutSeconds: 2
    failureThreshold: 6

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "250m"
    memory: "256Mi"

worker:
  name: personal-tracker-worker
  replicas: 1
  image:
    repository: iacobstev/personal-tracker-app
    tag: latest
  command: ["celery"]
  args: ["-A", "app.celery_app.celery_app", "worker", "--loglevel=info"]
  env:
    DB_TYPE: "postgres"
    PG_HOST: "postgres"
    PG_USER: "postgres"
    PG_PASSWORD: "postgres"
    PG_DB: "personal_tracker"
    CELERY_BROKER_URL: "redis://personal-tracker-redis-master:6379/0"
    CELERY_RESULT_BACKEND: "redis://personal-tracker-redis-master:6379/0"

beat:
  name: personal-tracker-beat
  replicas: 1
  image:
    repository: iacobstev/personal-tracker-app
    tag: v4
  command: ["celery"]
  args: ["-A", "app.celery_app.celery_app", "beat", "--loglevel=info"]

frontend:
  name: personal-tracker-frontend
  replicas: 1
  image:
    repository: iacobstev/personal-tracker-frontend
    tag: v1
  containerPort: 80

  service:
    type: NodePort
    port: 80
    targetPort: 80
    nodePort: 30080

  configMap:
    name: frontend-config
    apiUrl: "http://personal-tracker-app:5000"

redis:
  architecture: standalone
  auth:
    enabled: false
  master:
    persistence:
      enabled: false

postgresql:
  auth:
    username: tracker
    password: tracker
    database: tracker
  primary:
    persistence:
      enabled: true
      size: 1Gi

appConfig:
  name: app-config
  data:
    DB_CONNECT_DELAY: "3"
    DB_CONNECT_RETRIES: "10"
    DB_TYPE: "postgres"
    PG_DB: "tracker"
    PG_HOST: "personal-tracker-postgresql"
    PG_PORT: "5432"
    PG_USER: "tracker"
