apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  DB_TYPE: "postgres"
  PG_HOST: "postgres"
  PG_PORT: "5432"
  PG_DB: "tracker"
  PG_USER: "tracker"
  DB_CONNECT_RETRIES: "10"
  DB_CONNECT_DELAY: "3"
