apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.beat.name }}
spec:
  revisionHistoryLimit: 2
  replicas: {{ .Values.beat.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.beat.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.beat.name }}
    spec:
      containers:
        - name: beat
          image: "{{ .Values.beat.image.repository }}:{{ .Values.beat.image.tag }}"
          securityContext:
            runAsNonRoot: true
            runAsUser: {{ .Values.securityContext.runAsUser }}
            runAsGroup: {{ .Values.securityContext.runAsGroup }}
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          command: {{ .Values.beat.command | toJson }}
          args: {{ .Values.beat.args | toJson }}
          resources:
            requests:
              cpu: {{ .Values.beatResources.requests.cpu }}
              memory: {{ .Values.beatResources.requests.memory }}
            limits:
              cpu: {{ .Values.beatResources.limits.cpu }}
              memory: {{ .Values.beatResources.limits.memory }}
          envFrom:
            - configMapRef:
                name: {{ .Values.configMap.name }}
            - secretRef:
                name: {{ .Values.secret.name }}
