apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.worker.name }}
spec:
  revisionHistoryLimit: 2
  replicas: {{ .Values.worker.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.worker.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.worker.name }}
    spec:
      containers:
        - name: worker
          image: "{{ .Values.worker.image.repository }}:{{ .Values.worker.image.tag }}"
          securityContext:
            runAsNonRoot: true
            runAsUser: {{ .Values.securityContext.runAsUser }}
            runAsGroup: {{ .Values.securityContext.runAsGroup }}
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          command: {{ .Values.worker.command | toJson }}
          args: {{ .Values.worker.args | toJson }}
          resources:
            requests:
              cpu: {{ .Values.workerResources.requests.cpu }}
              memory: {{ .Values.workerResources.requests.memory }}
            limits:
              cpu: {{ .Values.workerResources.limits.cpu }}
              memory: {{ .Values.workerResources.limits.memory }}
          env:
            {{- range $key, $value := .Values.worker.env }}
            {{- if ne $key "PG_PASSWORD" }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            {{- end }}
            - name: PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: {{ .Values.secret.pgPasswordKey }}
