apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.worker.name }}
spec:
  replicas: {{ .Values.worker.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.worker.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.worker.name }}
    spec:
      containers:
        - name: worker
          image: "{{ .Values.worker.image.repository }}:{{ .Values.worker.image.tag }}"
          securityContext:
            runAsNonRoot: true
            runAsUser: 10001
            runAsGroup: 10001
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          command: {{ .Values.worker.command | toJson }}
          args: {{ .Values.worker.args | toJson }}
          resources:
            requests:
              cpu: {{ .Values.workerResources.requests.cpu }}
              memory: {{ .Values.workerResources.requests.memory }}
            limits:
              cpu: {{ .Values.workerResources.limits.cpu }}
              memory: {{ .Values.workerResources.limits.memory }}

          env:
            # 1. TOATE variabilele din values.yaml, EXCEPT PG_PASSWORD
            {{- range $key, $value := .Values.worker.env }}
            {{- if ne $key "PG_PASSWORD" }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            {{- end }}

            # 2. PG_PASSWORD vine din Secret
            - name: PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: PG_PASSWORD
