name: Deploy to Kubernetes

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Set image tag
        run: echo "TAG=${GITHUB_SHA}" >> $GITHUB_ENV

      - name: Update app deployment
        run: kubectl set image deployment/personal-tracker-app app=iacobstev/personal-tracker-app:${TAG}

      - name: Update worker deployment
        run: kubectl set image deployment/personal-tracker-worker worker=iacobstev/personal-tracker-app:${TAG}

      - name: Update beat deployment
        run: kubectl set image deployment/personal-tracker-beat beat=iacobstev/personal-tracker-app:${TAG}

      - name: Rollout status app
        run: kubectl rollout status deployment/personal-tracker-app

      - name: Rollout status worker
        run: kubectl rollout status deployment/personal-tracker-worker

      - name: Rollout status beat
        run: kubectl rollout status deployment/personal-tracker-beat
